
services:
  cron:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        user: ${ENV}_${APP_NAME}_user
        PHP_VERSION: ${PHP_VERSION:-8.3}
        ENABLE_MONGODB_EXTENSION: ${ENABLE_MONGODB_EXTENSION:-false}
        ENABLE_MONGODB_EXTENSION_VERSION: ${ENABLE_MONGODB_EXTENSION_VERSION:-1.20.0}
    container_name: ${ENV}_${APP_NAME}_cron
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ../:/var/www:delegated
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini:ro
    environment:
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-512M}
      PHP_UPLOAD_MAX_FILESIZE: ${PHP_UPLOAD_MAX_FILESIZE:-30M}
      PHP_POST_MAX_SIZE: ${PHP_POST_MAX_SIZE:-30M}
      PHP_MAX_EXECUTION_TIME: ${PHP_MAX_EXECUTION_TIME:-60}
    networks:
      mynet: {}
    command: sh -c "while :; do php /var/www/artisan schedule:run >> /dev/null 2>&1; sleep 60; done"

networks:
  mynet:
    driver: bridge
    name: ${ENV}_${APP_NAME}_network